blog/urls.py
from django.conf.urls import url
from blog import views

# app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^preview/(?P<pk>[0-9]+)/$', views.preview, name='preview'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),
    url(r'^about/$', views.about, name='about'),
    url(r'^preview_about/$', views.preview_about, name='preview_about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'check_code', views.check_code, name='check_code'),
]

dream_blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
import xadmin
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^all/rss/$', AllPostRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

#  给UEditor设置
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags
from ckeditor_uploader.fields import RichTextUploadingField


@python_2_unicode_compatible
class Category(models.Model):
    """
    文章分类
    """
    name = models.CharField(max_length=60, verbose_name='分类')  # 分类名称
    is_pub = models.BooleanField(default=True, verbose_name='是否公开')  # 是否公开

    created_time = models.DateTimeField(verbose_name='创建日期')  # 创建日期
    modified_time = models.DateTimeField(null=True, verbose_name='修改日期')  # 修改日期

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']  # 按哪个排序

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """
    文章标签
    """
    name = models.CharField(max_length=100, verbose_name='标签')  # 标签名称
    is_pub = models.BooleanField(default=True, verbose_name='是否公开')  # 是否公开

    created_time = models.DateTimeField(verbose_name='创建日期')  # 创建日期
    modified_time = models.DateTimeField(verbose_name='修改日期')  # 修改日期

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']  # 按哪个排序

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=70, verbose_name='标题')  # 标题
    body = RichTextUploadingField(config_name='default', verbose_name='正文')  # ckeditor,配置在工程settings中
    create_time = models.DateTimeField(verbose_name='发布日期')  # 发布时间
    modified_time = models.DateTimeField(verbose_name='修改日期')  # 修改时间
    excerpt = models.TextField(max_length=200, blank=True, verbose_name='摘要')  # 摘要
    is_pub = models.BooleanField(default=True, verbose_name='是否公开')  # 是否公开
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')  # 是否推荐
    is_original = models.BooleanField(default=True, verbose_name='是否原创')  # 是否原创
    category = models.ForeignKey(Category, verbose_name='分类')  # 分类
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')  # 标签
    author = models.ForeignKey(User, verbose_name='作者')  # 作者
    views = models.PositiveIntegerField(default=0, verbose_name='访问量')  # 点击量

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']  # 按哪个排序

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        对象对应的URL
        :return: 
        """
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        """
        更新访问量
        :return: 
        """
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        # 如果摘要没有填写，则自动生成
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:74]
        super(Post, self).save(*args, **kwargs)


@python_2_unicode_compatible
class About(models.Model):
    """
    关于 model
    """
    title = models.CharField(max_length=200, verbose_name='标题')  # 标题
    created_time = models.DateTimeField(verbose_name='发布日期')  # 发布时间
    body = RichTextUploadingField(config_name='default', verbose_name='正文')  # ckeditor,配置在工程settings中
    modified_time = models.DateTimeField(verbose_name='修改日期')  # 修改时间
    is_pub = models.BooleanField(default=True, verbose_name='是否公开')  # 是否公开
    views = models.PositiveIntegerField(default=0, verbose_name='访问量')  # 点击量

    class Meta:
        verbose_name = '关于'
        verbose_name_plural = verbose_name

    def increase_views(self):
        """
        更新访问量
        :return: 
        """
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class FriendSite(models.Model):
    """
    友情链接，链接互换
    """
    site_name = models.CharField(max_length=20, blank=False, verbose_name='站点名称')  # 站点名称
    site_url = models.URLField(max_length=150, blank=False, verbose_name='站点地址')  # 站点地址
    admin_name = models.CharField(max_length=30, verbose_name='站长名称')  # 站长名称
    admin_contact = models.CharField(max_length=200, verbose_name='站长联系方式')  # 站长联系方式
    created_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间
    modified_time = models.DateTimeField(verbose_name='修改时间')  # 修改时间
    is_pub = models.BooleanField(default=False, verbose_name='是否发布')  # 默认不发布

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name


@python_2_unicode_compatible
class VisitRecord(models.Model):
    """
    游客访问记录 
    """
    http_host = models.CharField(max_length=30, verbose_name='host')  # HTTP_HOST
    http_path = models.CharField(max_length=500, verbose_name='path')  # 访问链接
    http_user_agent = models.CharField(max_length=350, verbose_name='agent')  # 客户端的user-agent字符串
    ip = models.CharField(max_length=20, verbose_name='ip')  # 客户端的IP地址
    server_name = models.CharField(max_length=40, verbose_name='server_name')  # 服务器的主机名
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='请求时间')  # 访问时间

    class Meta:
        verbose_name = '访问记录'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip


@python_2_unicode_compatible
class VisitStatistics(models.Model):
    """
     站点运营统计数据，每天的有效访问量，访问ip等 
    """
    today_visit = models.PositiveIntegerField(default=0, verbose_name='访问量')  # 今日访问量

    created_date = models.DateField(unique=True, editable=True, verbose_name='日期')  # 日期

    class Meta:
        verbose_name = '运营统计'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s 访问量" % self.created_date.strftime('%Y-%m-%d')


@python_2_unicode_compatible
class BlackList(models.Model):
    """
    黑名单，可以记录危险操作的ip，并可选择禁止访问
    """

    # 拒绝原因
    DENY_REASON_CHOICES = (
        ('1', '爬虫'),
        ('2', '破解密码'),
        ('3', '不友好用户'),
    )
    ip = models.CharField(max_length=20, unique=True, verbose_name='ip地址')
    is_disable = models.BooleanField(default=True, verbose_name='是否禁止')  # 是否禁止访问，默认禁止访问
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified_time = models.DateTimeField(null=True, verbose_name='修改时间')
    deny_reason = models.CharField(max_length=20, choices=DENY_REASON_CHOICES, default='1', verbose_name='禁止原因')  # 拒绝原因
    remarks = models.TextField(null=True, blank=True, verbose_name='备注')  # 备注

    class Meta:
        verbose_name = '黑名单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip


@python_2_unicode_compatible
class Contact(models.Model):
    """
    游客留言
    """
    name = models.CharField(max_length=10, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    subject = models.TextField(max_length=100, verbose_name='主题')
    content = models.TextField(max_length=400, verbose_name='内容')

    is_check = models.BooleanField(default=False, verbose_name='是否已读')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建日期')

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    在django的用户模型上扩展自定义User
    """
    nickname = models.CharField(max_length=50, blank=False, null=False, unique=True, verbose_name='昵称')  # 昵称，GitHub的用户名
    url = models.URLField(max_length=255, blank=True, verbose_name='个人主页')  # 个人主页
    photo = models.URLField(max_length=255, blank=True, verbose_name='头像')  # 头像

    class Meta(AbstractUser.Meta):
        verbose_name = '用户'
        verbose_name_plural = verbose_name

        def __str__(self):
            return self.nickname

blog/forms.py
from django import forms


class ContactForm(forms.Form):
    """
    联系我表单
    """
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '你的名字'}),
                           max_length=10,
                           error_messages={'required': '名称不能为空', 'max_length': '不超过10字'})
    subject = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '留言的主题'}),
                              max_length=100,
                              error_messages={'required': '主题不能为空', 'max_length': '不超过100字'})
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': '你的邮箱'}),
                             error_messages={'required': '邮箱不能为空'})
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': '联系内容'}),
                              max_length=400,
                              error_messages={'required': '内容不能为空', 'max_length': '不超过400字'})
    check_code = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '验证码'}),
                                 error_messages={'required': '验证码不能为空'})

blog/templates/blog/contact.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>VanBlog-留言</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- cdn -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://cdn.bootcss.com/jquery.form/3.37.0/jquery.form.min.js"></script>

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- js -->
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body id="page">
<div id="particles-js"></div>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Van</b>Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="主页">主页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="留言">留言</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="Search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">留言</h1>
                <article class="post">
                    <div class="entry-content clearfix">

                        <form action="{% url 'blog:contact' %}" method="post" class="contact-form" id="contact">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <span class="form-require">*</span>
                                    <label for="{{ form.name.id_for_label }}">名字</label>
                                    {{ form.name }}
                                    {{ form.name.errors }}

                                    <span class="form-require">*</span>
                                    <label for="{{ form.email.id_for_label }}">邮箱</label>
                                    {{ form.email }}
                                    {{ form.email.errors }}

                                    <span class="form-require">*</span>
                                    <label for="{{ form.subject.id_for_label }}">留言主题</label>
                                    {{ form.subject }}
                                    {{ form.subject.errors }}

                                    <span class="form-require">*</span>
                                    <label for="{{ form.content.id_for_label }}">留言内容</label>
                                    {{ form.content }}
                                    {{ form.content.errors }}

                                    <span class="form-require">*</span>
                                    <label for="{{ form.check_code.id_for_label }}">验证码</label>
                                    <img id="check_code" src="{% url 'blog:check_code' %}" onclick="ChangeCode(this)">
                                    {{ form.check_code }}
                                    {{ form.check_code.errors }}
                                    <button class="btn-send btn-5 btn-5b" type="submit">提交</button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>网站已经运行：{% get_run_day_count %}天</p>
                    {% get_total_visit_count as total_count %}
                    <p>总访问量：{{ total_count.total_visit }}次 | 今日访问量：{% get_today_visit_count %}次 | 游客IP：{% get_ip_count %}个</p>
                    <p class="social">
                        <a href="http://github.com/fanlion">
                            <span class="fa fa-github" style="font-size: 20px;"></span>
                        </a>
                        <a href="http://www.jianshu.com/u/634dfeefc2c3">
                            <span class="fa fa-book" style="font-size: 20px;"></span>
                        </a>
                        <a href="http://weibo.com/u/3775148554">
                            <span class="fa fa-weibo" style="font-size: 20px;"></span>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">主页</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="{% url 'blog:contact' %}">留言</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/particles.min.js' %}"></script>
<script src="{% static 'blog/js/particles-app.js' %}"></script>
<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
<script>
    function ChangeCode(ths) {
        ths.src = $('#check_code').attr('src').split('?')[0] + '?' + Math.random();
    }

    $(document).ready(function () {

        $('#contact').submit(function () {
            var options = {
                type: 'post',
                dataType: 'json',
                success: afterSubmit
            };

            function afterSubmit(responseText) {
                swal("提示", responseText.result, "info");
                var new_url = $('#check_code').attr('src').split('?')[0] + '?' + Math.random();
                $('#check_code').attr('src', new_url);
            }

            $(this).ajaxSubmit(options);
            return false; // 阻止默认表单提交
        });

    });
</script>

</body>
</html>

blog/templates/blog/detail.html
{% load staticfiles %} {% load blog_tags %}
<!DOCTYPE html>
<html>

<head>
    <title>VanBlog-{{ post.title }}</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- cdn -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <style>

    </style>

</head>

<body>
<!-- 粒子效果 -->
<div id="particles-js"></div>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Van</b>Blog</a></h1>
                </div>
            </div>
            <!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="主页">主页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="留言">留言</a></li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon"
                                                       class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="Search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">


    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                                <span class="post-category">
                                <a class="fa fa-tag"
                                   href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}
                                </a>
                            </span>

                            <span class="post-date"><a class="fa fa-calendar"
                                                       href="{% url 'blog:archives' post.create_time.year post.create_time.month %}"><time
                                    class="entry-date"
                                    datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#"
                                                         class="fa fa-user">{{ post.author.nickname }}</a></span>
                            {# <span class="comments-link"><a href="#">{{ comment_list.count }} 评论</a></span>#}
                            <span class="views-count"><a href="#" class="fa fa-eye">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>
                            {{ post.body | safe }}
                        </p>
                    </div>

                </article>

                <!-- 评论 -->
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表你的评论</h3>
                    <form class="comment-form" action="#" method="post">
                        <div class="row">
                            <div class="col-md-4">
                                <span class="form-require">*</span>
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" placeholder="你的大名" required>
                            </div>
                            <div class="col-md-4">
                                <span class="form-require">*</span>
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" placeholder="你的邮箱(不会公开)" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="url" id="id_url" name="url" placeholder="个人主页（没有就算了)">
                            </div>
                            <div class="col-md-12">
                                <span class="form-require">*</span>
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" placeholder="你的伟大评论" required></textarea>
                            </div>
                            <div class="col-md-12">
                                <span class="form-require">*</span>
                                <label for="check_code">验证码: </label>
                                <img id="check_code" src="{% url 'blog:check_code' %}" onclick="ChangeCode(this)">
                                <input type="text" id="id_verify_code" name="verify_code" placeholder="验证码(点击验证码可刷新验证码)"
                                       required>
                            </div>

                            <div class="col-md-12">
                                <input id="id_post_id" type="hidden" value="{{ post.pk }}">
                                <button type="button" class="comment-btn" id="send_comment">发表伟大的评论</button>
                            </div>
                        </div>
                        <!-- row -->
                    </form>

                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ comments.count }}</span> 条评论</h3>
                        <div class="comment-list">
                            {% for comment in comments %}
                                <div class="comment-item">
                                    <span class="nickname">{{ comment.nick_name }}</span>
                                    <time class="submit-date">{{ comment.created_time }}</time>
                                    <div class="text">
                                        {{ comment.content }}
                                    </div>
{#                                    <div class="comment-tool">#}
{#                                        <a class="fa fa-thumbs-o-up">{{ comment.star }}赞</a>#}
{#                                        <a class="fa fa-thumbs-o-down">{{ comment.un_star }}踩</a>#}
{#                                    </div>#}
                                </div>
                            {% empty %}
                                <span>暂无评论</span>
                            {% endfor %}
                        </div>
                    </div>
                </section>
            </main>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>网站已经运行：{% get_run_day_count %}天</p>
                    {% get_total_visit_count as total_count %}
                    <p>总访问量：{{ total_count.total_visit }}次 | 今日访问量：{% get_today_visit_count %}次 |
                        游客IP：{% get_ip_count %}个</p>
                    <p class="social">
                        <a href="http://github.com/fanlion">
                            <span class="fa fa-github fa-github" style="font-size: 20px;"></span>

                        </a>
                        <a href="http://www.jianshu.com/u/634dfeefc2c3">
                            <span class="fa fa-book" style="font-size: 20px;"></span>
                        </a>
                        <a href="http://weibo.com/u/3775148554">
                            <span class="fa fa-weibo" style="font-size: 20px;"></span>
                        </a>

                    </p>
                </div>

            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="{% url 'blog:contact' %}">留言</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/particles.min.js' %}"></script>
<script src="{% static 'blog/js/particles-app.js' %}"></script>
<script src="{% static 'blog/js/detail.js' %}"></script>
<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
<script>
    $(document).ready(function () {
        // 评论表单提交
    $('#send_comment').click(function () {
        var nick_name = $('#id_name').val().trim();
        var email = $('#id_email').val().trim();
        var home_url = $('#id_url').val().trim();
        var content = $('#id_comment').val().trim();
        var verify_code = $('#id_verify_code').val().trim();
        var post_id = $('#id_post_id').val().trim();
        //trigger 事件执行完后，浏览器会为submit按钮获得焦点
        $("form .required:input").trigger("blur");

        var numError = $(".form-error").length;
        if(numError){
            return false;
        }

        $.ajax({
            url: '{% url "comments:comment" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                "nick_name": nick_name,
                "email": email,
                "home_url": home_url,
                "verify_code": verify_code,
                "content": content,
                "post_id": post_id
            },
            success: function (data) {
                swal({
                    title: "消息",
                    text: data.result,
                    type: "success"
                }, function () {
                    window.location.reload();
                });
            },
            error: function () {
                swal({
                    title: "异常",
                    text: "未能发表伟大评论",
                    type: "error"
                }, function () {
                    window.location.reload();
                });
            }
        });
    });
    })
</script>
</body>

</html>